- hosts: localhost

  tasks:

    - name: Install NVM
      shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "/home/vagrant/"
        creates: "/home/vagrant/.nvm/nvm.sh"

    - name: Install Node
      shell: >
        . /home/vagrant/.nvm/nvm.sh && nvm install 12.16.1
      args:
        executable: /bin/bash
        chdir: "/home/vagrant"
        creates: "/home/vagrant/.nvm/versions/12.16.1"

    - name: Install pm2 package
      npm:
        name: pm2
        global: yes
        state: present

    - name: Symbolic link for node
      file:
          src: "/home/vagrant/.nvm/versions/node/v12.16.1/bin/node"
          dest: "/usr/local/bin/node"
          state: link
      become: yes

    - name: Symbolic link for pm2
      file:
          src: "/home/vagrant/.nvm/versions/node/v12.16.1/bin/pm2"
          dest: "/usr/local/bin/pm2"
          state: link
      become: yes

    - name: Install epel-release
      yum:
          name: epel-release
          state: present

    - name: Install nginx
      yum:
          name: nginx
          state: present
      become: yes
