- hosts: localhost

  tasks:

    - name: Install NVM version 
      shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Install node version 12.16.1
      shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 12.16.1
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/12.16.1"

    - name: Install pm2 package
      npm:
        name: pm2
        global: yes
        state: present

    - name: Symbolic link for node
      file:
          src: "{{ ansible_env.HOME }}/.nvm/versions/node/v12.16.1/bin/node"
          dest: "/usr/local/bin/node"
          state: link
      become: yes

    - name: Symbolic link for pm2
      file:
          src: "{{ ansible_env.HOME }}/.nvm/versions/node/v12.16.1/bin/pm2"
          dest: "/usr/local/bin/pm2"
          state: link
      become: yes
